spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    host: localhost
    port: 13500
    database: eca
    username: root
    password: mongodb
    authentication-database: admin

server:
  port: 0

eureka:
  instance:
    # using Service Name and Random UUID to create a unique Instance ID - for port is dynamic ( it means port = 0 )
    instance-id: ${spring.application.name}:${random.value}